name: Test

on: [push]

jobs:
  test:    
    runs-on: ubuntu-latest
    name: CI Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        uses: ./.github/actions/ci_testing
